services:
  app:
    
    build: .
    image: libreria-app:latest
    container_name: libreria-api
    ports:
        - "8080:8080"
    volumes:
        - h2_data:/data
    environment:
      
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/libreria_db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_H2_CONSOLE_ENABLED=true 
volumes:
  h2_data:
    